import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Zap, AlertTriangle, CheckCircle2, Clock } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../components/shared/Toast';
import FileUploadZone from '../components/shared/FileUploadZone';
import ItemTypeSelector from '../components/shared/ItemTypeSelector';
import RunUsageMeter from '../components/shared/RunUsageMeter';
import Button from '../components/ui/Button';
import { RUNS, RUN_ITEMS, ITEM_TYPES } from '../data/mockData';

function formatBytes(bytes) {
  if (!bytes) return '';
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function InfoCard({ title, color, children }) {
  return (
    <div className={`rounded-xl border p-4 ${color}`}>
      <h3 className="text-sm font-bold mb-2">{title}</h3>
      <ul className="space-y-1.5 text-xs leading-relaxed">{children}</ul>
    </div>
  );
}

function InfoItem({ icon, text }) {
  return (
    <li className="flex items-start gap-2">
      <span className="flex-shrink-0 mt-0.5">{icon}</span>
      <span>{text}</span>
    </li>
  );
}

export default function RunRequestPage() {
  const { user } = useAuth();
  const navigate  = useNavigate();
  const showToast = useToast();

  const userRuns  = RUNS.filter(r => r.userId === (user?.id ?? 'u4'));
  const runsUsed  = userRuns.length;
  const maxRuns   = 3;
  const isMaxed   = runsUsed >= maxRuns;

  const [file, setFile]             = useState(null);
  const [sourceType, setSourceType] = useState(null);
  const [selectedTypes, setTypes]   = useState([]);
  const [quantity, setQuantity]     = useState(15);
  const [generating, setGenerating] = useState(false);
  const [typeError, setTypeError]   = useState('');

  function handleFileSelected(f, st) {
    setFile(f);
    setSourceType(st);
  }

  async function handleRequestRun() {
    if (!file)               { showToast('Please upload a source file.', 'error'); return; }
    if (!selectedTypes.length) { setTypeError('Select at least one item type.'); return; }
    setTypeError('');
    setGenerating(true);

    // Simulate processing — in production this hits the API
    const newRunId = `run-${Date.now()}`;
    await new Promise(r => setTimeout(r, 2500));

    const newRun = {
      id: newRunId,
      userId: user?.id ?? 'u3',
      status: 'completed',
      sourceType,
      sourceFileName: file.name,
      sourceFileSize: file.size,
      sourcePageCount: sourceType === 'document' ? null : null,
      sourceDuration: null,
      itemTypes: selectedTypes,
      itemCount: Math.min(quantity, 10),
      requestedCount: quantity,
      createdAt: new Date().toISOString(),
      completedAt: new Date().toISOString(),
      estimatedSeconds: 150,
      notes: '',
      projectId: null,
    };
    RUNS.push(newRun);

    // Seed a few stub items so the results page isn't empty
    const stubItems = selectedTypes.slice(0, 3).map((type, idx) => {
      const typeMeta = ITEM_TYPES.find(t => t.id === type);
      return {
        id: `item-new-${Date.now()}-${idx}`,
        runId: newRunId,
        type,
        stem: `[Sample] Generated ${typeMeta?.label ?? type} item from "${file.name}". (Replace with real AI output.)`,
        options: type === 'mcq' || type === 'scenario'
          ? ['A. Option one', 'B. Option two', 'C. Option three', 'D. Option four']
          : null,
        correctAnswer: type === 'mcq' || type === 'scenario' ? 'A' : type === 'true-false' ? 'True' : 'sample answer',
        explanation: 'This explanation will be generated by the AI model.',
        sourceRef: sourceType === 'document'
          ? { type: 'page', pageNumber: idx + 1 }
          : { type: 'clip', startSeconds: idx * 60, endSeconds: idx * 60 + 45 },
        userReaction: null,
        notes: '',
        customized: false,
        originalStem: null,
        originalOptions: null,
        originalCorrectAnswer: null,
        addedToLists: [],
        createdAt: new Date().toISOString(),
      };
    });
    RUN_ITEMS.push(...stubItems);

    showToast('Run completed! Reviewing your items.', 'success');
    navigate(`/runs/${newRunId}`);
  }

  const estimatedTime = selectedTypes.length <= 2 ? '1–2 min' : selectedTypes.length <= 4 ? '2–4 min' : '4–6 min';

  return (
    <div className="max-w-7xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-navy">Generate Items</h1>
        <p className="text-sm text-gray-500 mt-1">Upload your source, select item types, and request a run.</p>
      </div>

      {isMaxed && (
        <div className="mb-6 flex items-start gap-3 rounded-xl border border-amber-300 bg-amber-50 px-4 py-3" role="alert">
          <AlertTriangle size={18} className="text-amber-600 flex-shrink-0 mt-0.5" aria-hidden="true" />
          <p className="text-sm text-amber-800">
            <strong>Run limit reached.</strong> You've used all {maxRuns} runs. Contact support or wait for the next billing period.
          </p>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* ── Left column: form ── */}
        <div className="lg:col-span-2 space-y-6">

          {/* Run quota */}
          <RunUsageMeter runsUsed={runsUsed} maxRuns={maxRuns} showDetails={runsUsed >= 2} />

          {/* File upload */}
          <div className="bg-white rounded-2xl border border-lgray-200 shadow-card p-5">
            <h2 className="text-sm font-bold text-navy mb-1">1 — Upload Source</h2>
            <p className="text-xs text-gray-400 mb-4">Upload a document, audio, or video file to generate items from.</p>
            <FileUploadZone
              onFileSelected={handleFileSelected}
              disabled={isMaxed || generating}
            />
            {file && sourceType && (
              <div className="mt-3 rounded-lg bg-green-50 border border-green-200 px-3 py-2 flex items-center gap-2">
                <CheckCircle2 size={14} className="text-green-600 flex-shrink-0" aria-hidden="true" />
                <p className="text-xs text-green-700">
                  {sourceType === 'document'
                    ? `We'll generate items based on each page of "${file.name}". More pages = more items available.`
                    : `We'll generate items from content segments in "${file.name}". Longer files = more items available.`}
                </p>
              </div>
            )}
          </div>

          {/* Item type selection */}
          <div className="bg-white rounded-2xl border border-lgray-200 shadow-card p-5">
            <h2 className="text-sm font-bold text-navy mb-1">2 — Select Item Types</h2>
            <p className="text-xs text-gray-400 mb-4">Choose one or more types. You can mix types in a single run.</p>
            <ItemTypeSelector
              selected={selectedTypes}
              onChange={v => { setTypes(v); setTypeError(''); }}
            />
            {typeError && (
              <p role="alert" className="mt-2 text-xs text-red-600">{typeError}</p>
            )}
          </div>

          {/* Quantity */}
          <div className="bg-white rounded-2xl border border-lgray-200 shadow-card p-5">
            <h2 className="text-sm font-bold text-navy mb-1">3 — Quantity</h2>
            <p className="text-xs text-gray-400 mb-4">Maximum items per run: 25. Actual count may be lower depending on source length.</p>
            <div className="flex items-center gap-4">
              <input
                type="range"
                min={1}
                max={25}
                value={quantity}
                onChange={e => setQuantity(Number(e.target.value))}
                disabled={isMaxed || generating}
                className="flex-1 accent-teal"
                aria-label="Number of items to generate"
              />
              <span className="text-2xl font-bold text-teal w-12 text-right tabular-nums">{quantity}</span>
            </div>
            <p className="text-xs text-gray-400 mt-1">items requested</p>
          </div>

          {/* Request button */}
          <div className="bg-white rounded-2xl border border-lgray-200 shadow-card p-5">
            <Button
              size="lg"
              className="w-full"
              leftIcon={generating ? undefined : Zap}
              loading={generating}
              disabled={isMaxed || generating}
              onClick={handleRequestRun}
            >
              {generating ? 'Generating your items…' : 'Request a Run'}
            </Button>
            <div className="flex items-center gap-1.5 mt-3 justify-center">
              <Clock size={13} className="text-gray-400" aria-hidden="true" />
              <p className="text-xs text-gray-400">Estimated time: {estimatedTime} depending on source length and item types selected.</p>
            </div>
          </div>
        </div>

        {/* ── Right column: roadmap info ── */}
        <div className="space-y-4">

          {/* What can you do */}
          <InfoCard title="✦ What you can do" color="border-teal/30 bg-teal/5 text-teal-800">
            <InfoItem icon="📄" text="Generate items from Documents, Audio, and Video files" />
            <InfoItem icon="🎯" text="Choose from 7 item types in a single run" />
            <InfoItem icon="📏" text="More pages / longer media = more items available" />
            <InfoItem icon="👍" text="Like or dislike each item" />
            <InfoItem icon="📝" text="Add internal notes per item and per run" />
            <InfoItem icon="✏️" text="Customize any item before exporting" />
            <InfoItem icon="📋" text="Save items to personal lists" />
            <InfoItem icon="⬇️" text="Export your list with full details" />
          </InfoCard>

          {/* Current limitations */}
          <InfoCard title="⚠ For now" color="border-amber-200 bg-amber-50 text-amber-900">
            <InfoItem icon="✅" text="Documents: up to 10 pages, 10 MB" />
            <InfoItem icon="✅" text="Audio: up to 60 min, 20 MB" />
            <InfoItem icon="✅" text="Video: up to 60 min, 50 MB" />
            <InfoItem icon="✅" text="7 item types supported" />
            <InfoItem icon="✅" text="Max 3 runs · Max 25 items per run" />
            <InfoItem icon="⏱" text="Execution time varies by source and types" />
          </InfoCard>

          {/* Coming soon */}
          <InfoCard title="🔜 Coming soon" color="border-teal-100 bg-white text-gray-700">
            <InfoItem icon="🔜" text="Difficulty levels per item" />
            <InfoItem icon="🔜" text="Share lists with your team" />
            <InfoItem icon="🔜" text="LMS & assessment platform integrations" />
            <InfoItem icon="🔜" text="Psychometric analytics dashboard" />
            <InfoItem icon="🔜" text="Accurate source location reference" />
            <InfoItem icon="🔜" text="Original source statement" />
          </InfoCard>

          {/* Long term */}
          <InfoCard title="🔭 On the horizon" color="border-navy/10 bg-navy/5 text-gray-600">
            <InfoItem icon="🔭" text="Spanish & Hindi language support" />
            <InfoItem icon="🔭" text="Mathematical equations & formulas" />
            <InfoItem icon="🔭" text="Image-based item generation" />
            <InfoItem icon="🔭" text="Auto and self-ranking" />
          </InfoCard>
        </div>
      </div>
    </div>
  );
}
